# Tutorial 9

# Evaluation (10 minutes)

# NumPy 

In [ ]:
import numpy as np

1. Run the following cell. What do you observe?

In [ ]:
a = np.array(["1", 4, 3])
print(a)

c = np.array([4, False, 3.3])
print(c)

2. Run the following cell and explain the problem here.

In [ ]:
L = [[0,1], [9,0,4], [4,2,7,6]]
L = np.array(L)
print(L)

3. Which data types can be used inside NumPy arrays?

<details>
  <summary>Click here</summary>

Numpy data types 

- bool
- int
- float
- str
- byte
- *complex*
- nan, inf
    
Syntax for complex numbers: `a = np.array([1+2j, 3+4j, 5+6j])`
 
</details>

### Working with NumPy arrays

4. The code below has the aim to replace all negative numbers of ``a`` with zero. We want to replace the following code and use NumPy instead. How can we achieve this in the shortest way?

In [ ]:
a = [6,3,7,9,4,2,6,8,0,-1,6,3,7,0,4,3,-4]

for i in range(len(a)):
    if a[i] < 0:
        a[i] = 0

print(a)

5. Explain the output. What does the following operation do?

In [ ]:
a = np.array([[1, 1],[1, 1]])
b = np.array([[1, 1],[1, 1]])

print(a*b)

6. What does the following operation do? What is the expected output?

In [ ]:
a.dot(b)

7. How do you select the element with value `9` in the following array?

In [ ]:
L = [[0,1,5], [9,0,4], [4,2,7]]

8. Run the following cell. How many dimensions has each array? 

In [2]:
A1 = np.zeros(5) + 3

A2 = np.full(5,3)

A3 = np.ones(5) +2

print(A1 == A2)
print(A2 == A3)

[ True  True  True  True  True]
[ True  True  True  True  True]


You can check the number of dimensions with the function ``ndim``. Try it out with A1. 

In [ ]:
print(A1.ndim)

9. How can we reshape ``b`` to a 2D array with two rows?

In [ ]:
b = np.ones(20)

10. Explain how the array B=``np.arange(12).reshape((3, 4))`` will look like. How many dimensions has B?

11. What are axes in NumPy? How can we modify A to concatenate A and B along axis 0?

In [4]:
A = np.full(16,3)

B=np.arange(12).reshape((3, 4))

print(A)
print(B)

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# Exercise

## **Task 1:**

a) Create a 1D NumPy array A with 12 consecutive numbers from 1 to 12.

b) Reshape A so that you can perform **matrix multiplication with A and B**.

c) Perform the multiplication and print the result.

## **Task 2:**

a) Create a NumPy array named ``time`` with 100 evenly spaced points from 0 to 1000 using ``np.linspace``.

Assume the position of an object is given by:

$$s(t)=0.5⋅t^2$$

Compute the position array corresponding to each time point.

b) Plot a position vs. time diagram using ``matplotlib`` following the steps below:

- Size of the figure: figsize = (8,5)
- Add a legend: $s(t) = 0.5 t^2$
- Label your axes and add the title "Position vs. Time". 

In [ ]:
# Your solution for NumPy operation

In [ ]:
# Plotting part
import matplotlib.pyplot as plt